services:
  mysql:
    image: mysql
    # este comando es para poner el plugin de autenticacion por defecto
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
    volumes:
      - mysql_data:/var/lib/mysql
    # cada vez que se pare el contenedor se reinicia
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
    # el depends_on sirve para decir que servicio se tiene que e
    # ejecutar antes
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data:


